name: JAVA CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Build
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: Upload code
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: .
  build-and-push-latest:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        env:
          user: max-bevelander-miro
        with:
          registry: ghcr.io
          username: ${{ env.user }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: app
          push: true
          tags: ghcr.io/${{ env.user }}/micronaut-app:1.0-${{ github.sha }},ghcr.io/${{ env.user }}/micronaut-app:latest
