name: JAVA CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Test
        run: ci/unit-test-app.sh
      - name: Build
        run: ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: .
